sudo: required
install: ./install.sh
script: make test
osx_image: xcode8.2
before_install: 
    brew update
# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
