exception VariableNotDefined of string
exception LLVMFunctionNotFound of string
exception ReturntypeNotMatch of string
exception VariableDeclarationNotMatch of string
exception UndefinedID of string

exception ShouldNotHappenUnlessCompilerHasBug of string
